### PR TITLE
Remove credentials for accessing private dependencies

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Now that UXP and all dependencies are open source, we no longer need
credentials to access private dependencies.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Keeping in draft until repo is open sourced.

### CODE REVIEW

**Comment by turkenh** [comment]
@hasheddan nats-proxy is also public now, I believe we can merge this.

**Review by turkenh — APPROVED** [review]
Better to rebase on the latest main to have another pass of CI.

**Comment by hasheddan** [comment]
@turkenh good idea! Could you also remove the github bot secret?

**Comment by turkenh** [comment]
> @turkenh good idea! Could you also remove the github bot secret?

Done.

**Pull request merged**
