### PR TITLE
Update Crossplane to v1.3.0-rc.0

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Updates Crossplane version to v1.3.0-rc.0.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

`make generate`

### CODE REVIEW

**Comment by turkenh** [comment]
Hmm, one caveat affecting our dev environment here:

Merging this will create a UXP 1.3.xxx from main and wesaas operator will upgrade existing UXP 1.3.xxx versions to this new version which would mean updating crossplane `v1.2.1` to `v1.3.0-rc.0` which does not fit our intention to only [auto-update patch versions](https://github.com/upbound/wesaas/issues/801). 

This is because UXP versions from the main so far does not conform to the assumption of UXP major.minor will always reflect upstream crossplane one. 
The good thing is this is only an issue for versions from main and affect only dev.

**Comment by hasheddan** [comment]
@turkenh does this also mean that wesaas will upgrade clusters automatically when we actually release `v1.3.0-up.1` and promote through environments? I don't think we should be updating hosted clusters in any scenario without the user asking for it explicitly or subscribing to latest from channel. It also might make sense to point Dev wesaas at latest commit on latest active release branch, rather than latest on `main`.

**Comment by muvaf** [comment]
@hasheddan does it make sense to have a GH action that will update the version here in `main` to the latest RC of Crossplane?

**Comment by hasheddan** [comment]
@muvaf that sounds like it could be useful! It would need to watch for any tags on Crossplane `master`, then run `make generate` before opening a PR 👍🏻

**Review by turkenh — APPROVED** [review]

**Pull request merged**
