### PR TITLE
[release-1.2] Sync values.yaml.tmpl with Crossplane v1.2.1

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Updates values.yaml.tmpl to be consistent with Crossplane v1.2.1, which
is currently specified as the CROSSPLANE_TAG.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
(cherry picked from commit 36bcd35b3f6683af04ad4354b0faf38abb59005d)

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Backport of #114

### CODE REVIEW

**Comment by muvaf** [comment]
Are you planning to make a release? Wonder if we should backport everything in `master` to `release-1.2` that is non-breaking when we want to do a new release of UXP before the next minor version release of Crossplane.

**Comment by muvaf** [comment]
Yeah I'm trying to figure out what's the best way forward with less friction. Because we don't have a patch release concept in this repo, i.e. no `1.2.1-up.1.1`, it feels like all non-breaking changes could just go to `release-1.2` as well to be released in `1.2.1-up.2`. If that's the case, then it's easier to merge all non-breaking changes into `release-1.2` only once we decide to make a release from that branch instead of opening two PRs for every change. The breaking ones would wait for `release-1.3`. What do you think?

**Comment by hasheddan** [comment]
> Because we don't have a patch release concept in this repo, i.e. no 1.2.1-up.1.1, it feels like all non-breaking changes could just go to release-1.2 as well to be released in 1.2.1-up.2.

Yeah this was one of the concerns I had with tracking Crossplane versions directly as it technically should force us to wait until a new minor release of Crossplane to add any UXP feature work (if we were adhering to semver). It sounds like we want to continue to add feature work before that happening, so I don't see another option with this versioning strategy than to continue backporting features.

> If that's the case, then it's easier to merge all non-breaking changes into release-1.2 only once we decide to make a release from that branch instead of opening two PRs for every change.

I think this is an anti-pattern for a few reasons and would prefer that each PR be evaluated for backport:
1. Bulk backporting removes the responsibility and evaluation of whether each change should be backported from the original author at the time of committing, which is the best time to make that distinction.
2. Bulk backporting creates a blocker for releases. We can't just release whenever we want because we cannot be sure that we have all the proper functionality in the branch. Releasing would require first scanning the `main` branch to see what should be added, which could create significant delay and is error-prone.
3. Bulk backporting means that any automated testing that runs periodically (which we don't currently have set up, but should) has less opportunity to run against incremental changes. If we bulk backport changes then run e2e / integration testing against it we have created a potentially large diff from the last time the tests were run, making it difficult to troubleshoot and identify what change caused the error.

We should be able to run a release on active branches at any time with confidence that the content of the build is well-tested and functional.

**Comment by turkenh** [comment]
> @AaronME did we happen to rotate the Upbound API token in this repo?

@hasheddan I am guessing you're asking this for the failed e2e test. 
You will need this fix: https://github.com/upbound/universal-crossplane/pull/100 since the token no longer being passed for forked PRs after the repo is made public.

**Comment by hasheddan** [comment]
@turkenh thanks! Will add 👍🏻

**Comment by AaronME** [comment]
> @AaronME did we happen to rotate the Upbound API token in this repo?

Not yet. I only did the CircleCI builds so far

**Review by turkenh — APPROVED** [review]
A rebase should fix push validation

**Comment by muvaf** [comment]
> It sounds like we want to continue to add feature work before that happening, so I don't see another option with this versioning strategy than to continue backporting features.

That is actually what I'm trying to figure out. For example, if we say that from `1.2.1-up.1` to `1.2.1-up.2`, there will be no **feature work** but only bug fixes, then what PRs to backport are clear; the ones we see as critical enough to warrant a new release, just like Crossplane. But if we say that we'll pile changes in `release-1.2` just to make sure they make it to the next release, then it's more like allowing **non-breaking feature work** to be introduced between `1.2.1-up.1` and `1.2.1-up.2` rather than just bug fixes.

If we choose former, then backporting isn't much work; it's done only for release-warranting bug fixes. But if it's the latter, then the only difference between `master` and the branch of the last release is breaking change commits, hence it'd be easier to merge all non-breaking commits in `master` to that release branch when we want to release the next `up.2` version (or maybe set up a bot to open the backport PR and merge automatically after approval) rather than opening two PRs for each change.

**Pull request merged**
